#!/usr/bin/env python3
"""Write the extension table at the end of src/mimeext.nv.

The table is the Rust crate mime_guess's `src/mime_types.rs` (MIT), at
the commit named below, which is itself drawn from Apache's
`mime.types`, jshttp's mime-db and MimeTypeMap.  Everything from the
line `// The extension table.` to the end of src/mimeext.nv is
replaced.

The preferred extension of a type is the one Python's
`mimetypes.guess_extension` picks from its built-in map, when that
extension is one the table lists for the type.  Otherwise it is the
first the table lists.  Only the types where the two differ are
written out.

The file is passed through `novo fmt` afterwards.

Run from the package root:  python3 tools/ext_table.py [mime_types.rs]
With no argument the file is fetched from GitHub at the pinned commit.
"""
import collections
import mimetypes
import re
import subprocess
import sys
import urllib.request

COMMIT = '90f3d09696f7c08dcac94ca2bb2a279383bb20ce'
URL = ('https://raw.githubusercontent.com/abonander/mime_guess/%s/src/mime_types.rs'
       % COMMIT)
MARK = '// The extension table.'


def rows_of(text):
    body = text[text.index('MIME_TYPES'):]
    rows = re.findall(r'\(\s*"([^"]+)",\s*&\[([^\]]*)\]\s*\)', body)
    rows = [(k, re.findall(r'"([^"]+)"', t)) for k, t in rows]
    keys = [k for k, _ in rows]
    assert keys == sorted(keys), 'the table is no longer sorted bytewise'
    assert len(set(keys)) == len(keys), 'the table has a duplicate extension'
    return rows


def preferred(rows):
    by_type = collections.OrderedDict()
    for ext, types in rows:
        for t in types:
            by_type.setdefault(t, []).append(ext)
    oracle = mimetypes.MimeTypes(filenames=())
    out = []
    for t, exts in by_type.items():
        g = oracle.guess_extension(t, strict=False)
        if g and g[1:] in exts and g[1:] != exts[0]:
            out.append((t, g[1:]))
    return out


def main():
    if len(sys.argv) > 1:
        text = open(sys.argv[1]).read()
    else:
        text = urllib.request.urlopen(URL).read().decode()
    rows = rows_of(text)
    lines = [MARK,
             '//',
             '// Generated by tools/ext_table.py from mime_guess %s,' % COMMIT[:12],
             '// src/mime_types.rs (MIT).  Sorted bytewise by extension, which is',
             '// what `find` searches.  Do not edit by hand.',
             '',
             'const ENTRIES: Int = %d' % len(rows),
             '',
             '// The extension of entry `i`, without its dot.  Every caller passes',
             '// an index below ENTRIES, so the last arm is the last entry.',
             'fn entry_ext(i: Int) -> Str',
             '    match i']
    for n, (ext, _) in enumerate(rows[:-1]):
        lines.append('        %d => "%s"' % (n, ext))
    lines += ['        _ => "%s"' % rows[-1][0], '',
              '// The media types of entry `i`, most prevalent first, joined by `,`.',
              '// The last arm is the last entry, as in `entry_ext`.',
              'fn entry_types(i: Int) -> Str',
              '    match i']
    for n, (_, types) in enumerate(rows[:-1]):
        lines.append('        %d => "%s"' % (n, ','.join(types)))
    lines += ['        _ => "%s"' % ','.join(rows[-1][1]), '',
              '// The extension to prefer for a media type, where it is not the first',
              '// the table lists, or `""`.',
              'fn preferred_of(media_type: Str) -> Str',
              '    match media_type']
    for t, ext in preferred(rows):
        lines.append('        "%s" => "%s"' % (t, ext))
    lines += ['        _ => ""', '']
    path = 'src/mimeext.nv'
    src = open(path).read()
    head = src[:src.index(MARK)] if MARK in src else src
    open(path, 'w').write(head + '\n'.join(lines))
    # The arms are aligned the way `novo fmt` prints them.
    subprocess.run(['novo', 'fmt', path], check=True, capture_output=True)
    print('%d entries written to %s' % (len(rows), path))


if __name__ == '__main__':
    main()
